### ISSUE TITLE
How to build swagger2raml?

### ISSUE THREAD

**Issue by RobBednark** [8x8Cloud/swagger2raml#18]
I'm not a Java developer.  How do I build `swagger2raml-1.0.0.jar`?

I installed the JDK, ran `gradle`, and it ran without errors, but I don't see any resulting `swagger2raml*.jar`

**Comment by mmatloka** [comment]
Hey,
You have to run the `shadow` task, so e.g. `gradlew shadow`. Jar will be in `dist` directory.

**Comment by RobBednark** [comment]
Thank you @mmatloka !  I also discovered I could download the jar from http://mvnrepository.com/artifact/com.8x8.cloud/swagger2raml/1.0.0

**Comment by mmatloka** [comment]
@RobBednark and from https://github.com/8x8Cloud/swagger2raml/releases
